name: Build PB Version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          # pip install -r requirements.txt
          echo "No extra dependencies to install"

      - name: Bundle Project
        run: |
          python3 Bundle.py main.py output.py
          python3 Bundle.py main.py output--no-annotate.py --no-annotate

      - name: Build Artifact Name
        run: |
          CODE_LEN=$(wc -c < output--no-annotate.py | xargs)
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          ARTIFACT_NAME="output[${CODE_LEN}]-${SHORT_SHA}"
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
          echo "- 代码长度: $CODE_LEN"
          echo "- 提交 SHA: $SHORT_SHA"
          echo "- 最终构件名: $ARTIFACT_NAME"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: output*
          if-no-files-found: error

      - name: Test
        run: |
          python3 output.py
          python3 output--no-annotate.py
